# Generated by Django 5.1.6 on 2025-02-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('matin', 'Matin'), ('après-midi', 'Après-midi'), ('nuit', 'Nuit')], max_length=20)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='employees',
            field=models.ManyToManyField(through='api.SaleEmployee', to='api.employee'),
        ),
        migrations.AddIndex(
            model_name='saleemployee',
            index=models.Index(fields=['sale', 'employee'], name='api_saleemp_sale_id_7d9593_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='api_sale_date_61ee18_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shift'], name='api_sale_shift_2c406a_idx'),
        ),
    ]
